# fly.toml app configuration file generated for abra on 2023-06-18T13:18:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "abra"
primary_region = "mad"

[http_service]
  internal_port = 2272
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
